import Head from 'next/head'
import React from 'react'
import Header from '../../globalComponents/Header/Header'
import LeftSideBar from '../../globalComponents/SideBars/LeftSideBar/LeftSideBar'
import RightSideBar from '../../globalComponents/SideBars/RightSideBar/RightSideBar'
import BottomBar from '../../mobileGlobalComponents/BottomBar/BottomBar'

interface IHomeLayoutProps {
  children: React.ReactNode
}

const HomeLayout = ( {children}:IHomeLayoutProps ) => {
  return (
    <div className='w-full flex justify-between items-center max-h-screen overflow-hidden'>
        <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <LeftSideBar />
      {children}
      <RightSideBar />

      <BottomBar />

    </div>
  )
}

export default HomeLayout